### ISSUE TITLE
UI Redesign - Desktop - Navigation Menu 

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/atmosphere_pro#204]
**Description**
The task is to implement the new design for the navigation menu in the desktop app.

**Assets and Design Screens** 
All assets and design screens have already been created.
- The Figma design can be found here  https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=1%3A2
- The Assets required can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=0%3A1

For help with using Figma please watch this short tutorial video
https://user-images.githubusercontent.com/69275762/192322842-2ac40f88-c396-4a66-933b-3c8abae516c3.mov

**Additional context**
- This work should be done on the UI_Redesign branch https://github.com/atsign-foundation/atmosphere_pro/tree/ui_redesign

**Comment by ketanvishwakarma** [comment]
@ksanty I'd like to work on this issue; could you please assign it to me?

**Comment by BAGEERADHAN** [comment]
@tinashe404  I would like to contribute to this issue. Can you assign this to me

**Comment by ksanty** [comment]
@ketanvishwakarma @BAGEERADHAN I've assigned you both to the issue.

**Comment by BAGEERADHAN** [comment]
@ksanty sorry to say that I'm unable to run the code over my system, can you help with that?

**Comment by tinashe404** [comment]
@BAGEERADHAN please could you tell us the issue/issues you are facing? Any error messages?

**Comment by ketanvishwakarma** [comment]
Hello, @tinashe404. Thank you for assigning this task to me. I'd like to inform you that I've created a PR for this issue [here](https://github.com/atsign-foundation/atmosphere_pro/pull/238). Please review and provide feedback as soon as you get a chance. Happy Hacktoberfest!!

**Comment by tinashe404** [comment]
Closing this as it has been completed by @ketanvishwakarma!
