### ISSUE TITLE
UI Redesign - Mobile - Settings

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atmosphere_pro#212]
**Description**
The task is to implement the new design for the settings menu in the mobile app. 

**Assets and Design Screens**
All assets and design screens have already been created.

- The Figma design can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=2%3A3
- The Assets required can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=0%3A1

For help with using Figma please watch this short tutorial video
https://user-images.githubusercontent.com/69275762/192322842-2ac40f88-c396-4a66-933b-3c8abae516c3.mov

**Additional context**
This work should be done on the UI_Redesign branch https://github.com/atsign-foundation/atmosphere_pro/tree/ui_redesign

**Comment by mkobuolys** [comment]
Hey, I would love to contribute to this 💙

**Comment by Chandram-Dutta** [comment]
Has any work been done in the ui_redesign branch? as i didnt find any difference from the main branch in terms of assets or screens or code??

**Comment by ksanty** [comment]
> Has any work been done in the ui_redesign branch? as i didnt find any difference from the main branch in terms of assets or screens or code??

@tinashe404 not sure are you able to respond.

**Comment by tinashe404** [comment]
@Chandram-Dutta No, no work has been done yet. Anyone working on the redesign will be working from that branch

**Comment by Chandram-Dutta** [comment]
@tinashe404 Ok...Cool, I have started working on it, added fonts and backgrounds (as in Figma File), will PR as I complete.

**Comment by tinashe404** [comment]
@Chandram-Dutta Sounds good! Let us know if you have any other questions.

**Comment by Chandram-Dutta** [comment]
Hey, @tinashe404 I pushed the changes in font and background in PR #224. Kindly review and if possible merge it. Happy Hacktoberfest!!!

**Comment by Chandram-Dutta** [comment]
@ksanty Can you please assign this issue to me. I have the code ready(will push it on 1st October to qualify for the hacktoberfest)

**Comment by ksanty** [comment]
> @ksanty Can you please assign this issue to me. I have the code ready(will push it on 1st October to qualify for the hacktoberfest)

Fabulous.  You're assigned now.

**Comment by Chandram-Dutta** [comment]
@ksanty #224 fixes this. Hope it gets qualified for Hacktoberfest!!

**Comment by ksanty** [comment]
Issue now merged and approved.
