### ISSUE TITLE
EncryptionService latest changes needs to be uptaken by the app

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/atmosphere_pro#245]
### Describe the bug

There's a recent change in EncryptionService that needs an atsign to be passed.

### Steps to reproduce

1. First update to the latest at_client version and do a flutter pub get

### Expected behavior

There should be no errors in the code.

### Screenshots

![Screenshot from 2023-01-12 19-22-00](https://user-images.githubusercontent.com/43639593/212124936-e620d3b9-62c0-4d4d-af1c-bb7aa23427ff.png)

### Smartphones

- Device: [e.g. Samsung Galaxy]
- OS: [e.g. Android]

### Were you using an atApplication when the bug was found?

atmospherePro

**Comment by sachins-geekyants** [comment]
Updated in trunk branch
