### ISSUE TITLE
Slow loading of contacts (if you have few)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atmosphere_pro#250]
### Describe the bug

Everytime I goto to the contacts page on the mobile app I get the blue spinny and it takes 10-15 seconds to load the contacts. Its really annoying as i know the data is locally on my phone so it should be instant.

### Steps to reproduce

1. First I have 20+ contacts then start the app and go to the contacts tab.
2. This does load but it can take 10-15 seconds which is super annoying!

### Expected behavior

Near Instant response

### Screenshots

video eaxmple

https://user-images.githubusercontent.com/6131216/217664653-5b473516-38a4-4af1-a6b6-4bf569cfeaac.mp4

### Smartphones

-Android Samsun S22 Ultra

### Were you using an atApplication when the bug was found?

atmospherepro

### Additional context

at sign used @ colin

**Comment by Sardar1208** [comment]
@cconstab Can you please share your atKey ?

**Comment by Sardar1208** [comment]
I can not reproduce this issue with this atSign on both trunk and play store version.

**Comment by sachins-geekyants** [comment]
Added a check in contacts package if data exists, we should not fetch it again, released with `at_contacts_flutter 4.0.10 ` version.

Assigning the ticket 0 SP till atPro is deployed with new contacts version.

**Comment by Sardar1208** [comment]
Added a fix in `at_contact_flutter`. Needs deployment and testing

**Comment by gkc** [comment]
@Sardar1208 @sachins-geekyants @ksanty Has this been verified as fixed?

**Comment by ksanty** [comment]
@sachins-geekyants @Sardar1208 I just tested on 2 different atSigns (@kims and @snooker68) and did not experience a blue spinny when accessing the contact screen.  When I refresh however I do experience the skeleton screen and a bit of a delay, which I think is normal behavior.

Might be worth having someone test on Android then close the ticket if ok.

**Comment by Sardar1208** [comment]
@ksanty Yes that is the expected behaviour. I think we can close this ticket

**Comment by ksanty** [comment]
> @ksanty Yes that is the expected behaviour. I think we can close this ticket

Great!  Closing now.
