### ISSUE TITLE
[Tracker] atmospherePro Desktop redesign

### ISSUE THREAD

**Issue by Sardar1208** [atsign-foundation/atmosphere_pro#294]
### _atmospherePro desktop redesign_
<a href="https://www.figma.com/file/nNys7N6irbXsvM2SbAEgl8/AtmospherePro-Desktop-V2?type=design&node-id=0-1&mode=design&t=Y3Dgg2kMWLSH3nY8-0" target="_blank" >design link</a>

### Setting up - 
Since this new design is completely different from the old atmospherePro design, we have decided to make this from scratch. Although some components are similar to the mobile version, so we can reuse those assets.

#### Theme - 
We will be setting up a theme so that we can easily add or update the theme of the app in the future.

#### Screens - 

<table>
    <tr><th>Screens / Widgets</th><th>Assigned to</th><th>Status</th></tr>
    <tr><td>Onboarding/splash screen</td><td>@sonle-geekyants</td><td>Done</td></tr>
    <tr><td>Side Navigation widget</td><td>@Sardar1208</td><td>Done</td></tr>
    <tr><td>Transfer file screen</td><td>@Sardar1208</td><td>Done</td></tr>
    <tr><td>Contact card widget</td><td> @sachins-geekyants  </td><td>Done</td></tr>
    <tr><td>Contacts screen</td><td> @sachins-geekyants </td><td>Done</td></tr>
    <tr><td>Add contact modal</td><td>--</td><td>Done</td></tr>
    <tr><td>Contact detail card</td><td>--</td><td>Done</td></tr>
    <tr><td>Groups screen</td><td>@sonle-geekyants</td><td>Done</td></tr>
    <tr><td>Add group modal</td><td>@sonle-geekyants</td><td>Done</td></tr>
    <tr><td>Detail group modal</td><td>@sonle-geekyants</td><td>Done</td></tr>
    <tr><td>Edit group modal</td><td>@sonle-geekyants</td><td>Done</td></tr>
    <tr><td>Trusted contacts screen</td><td>@Sardar1208</td><td>Done</td></tr>
    <tr><td>My files screen</td><td>@Sardar1208</td><td>Done</td></tr>
    <tr><td>Transfer history screen</td><td>@Sardar1208</td><td>Done</td></tr>
    <tr><td>Settings screen</td><td>@Sardar1208</td><td>Done</td></tr>
    <tr><td>Blocked contacts screen</td><td>@Sardar1208</td><td>Done</td></tr>

</table>

**Comment by AdiAr11** [comment]
Hi, if you need any help with the redesign, please let me know and i would be happy to help !!

**Comment by Sardar1208** [comment]
Closing this ticket
