### ISSUE TITLE
Atmosphere Desktop Daria Review Notes AUG 30 (version 55)

### ISSUE THREAD

**Issue by Dariamarg** [atsign-foundation/atmosphere_pro#323]
### Describe the bug

Following this [doc](https://docs.google.com/document/d/1UOUn2BuTaCAPewR7mVfUKMgGC-p_CkBpf9yYiljQNoQ/edit?usp=sharing)

- [x] Can we line up lines 
<img width="807" alt="Screenshot 2023-08-30 at 8 31 23 PM" src="https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/577f53cd-fc2c-4cae-9945-38301be6e665">

- [x] Icons - Match them + quality (some are thicker than others) - I have them all around 24px x 24px
- [x] “Upload Files” should be black but same size as select files (15px) + the little blurb below
- [x] “Contact Us” does nothing
- [x] atSigns not atsign (S capital) - On Transfer Screen
- [x] I can only add one file add a time - Enable multi-selection of files
- [x] Drag and Drop does not work when selecting file
- [x] Border selection is really odd on the edges (around display picture)
<img width="585" alt="Screenshot 2023-08-30 at 8 33 01 PM" src="https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/ec93f229-4860-4213-8ad8-dcd837ec5d8e">

- [x] Contacts has an animation while other don’t

https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/f54a1f41-cedb-4b49-809f-1f0faf8d7462

- [x] While searching, when a user is typing change search (magnifying glass) icon into “x” so they can clear it
- [x] (Transfer screen) Add “x” in the edges of contact cards so we can delete contacts post-selection
- [x] Add a “Are you sure you want to delete ____” pop up when deleting contacts on contact screen
- [x] Add a “Are you sure you want to delete ____” pop up when deleting contacts on block screen
- [x] Add little arrow on contacts so people know there is drop menu
<img width="158" alt="Screenshot 2023-08-30 at 8 34 44 PM" src="https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/909aa901-0d5a-4ca5-98c1-cc3862cdb247">

- [x] Refresh is not working (contacts and groups)
- [x] “Trusted” Screen background is a different color then the rest (check that all are #F8F8F8)
- [x] Make Trusted into a button as well 
- [x] Search Icon should match thickness of other (let me know if you need a cleaner file)
<img width="609" alt="Screenshot 2023-08-30 at 8 35 57 PM" src="https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/ea1cfa72-ab5a-4ee6-b7f3-03a8597659ee">

- [x] In Contacts Screen my intention was that groups takes up a 1/3 of the screen - for quicker access and to take advantage of the larger real estate on desktop

<img width="755" alt="Screenshot 2023-08-30 at 8 36 09 PM" src="https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/23bb8995-b81c-48f7-b55b-a6698babef5e">

### Steps to reproduce

See above

### Expected behavior

See above

### Screenshots

See above

### Smartphones

- Device: mac silicon chip 
- Version 55

### Were you using an atApplication when the bug was found?

atmospherePro

**Comment by ksanty** [comment]
@sachins-geekyants @Sardar1208 do you have any questions?  This is a super meaty ticket.  

@Dariamarg are these bugs or enhancements or both?

**Comment by sachins-geekyants** [comment]
@ksanty this is ready for review.

**Comment by Dariamarg** [comment]
Checked all the items: 

- [x] "Border selection is really odd on the edges (around display picture)" I don't see any border selection
- [x] "Search Icon should match thickness of other (let me know if you need a cleaner file)" Search Icon is still thinner, here is an SVG of a thicker one: 
![search](https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/a50bbc98-a546-4900-9862-ddbd2b0ddabc)

**Comment by Dariamarg** [comment]
First point, I don't see live in the current version (second is fixed)

Moving this back to Triage for next Sprint

**Comment by Sardar1208** [comment]
moving to next sprint

**Comment by Dariamarg** [comment]
Live in Version 60
