### ISSUE TITLE
Improve notification

### ISSUE THREAD

**Issue by sonle-geekyants** [atsign-foundation/atmosphere_pro#344]
### Describe the remaining issues

- Both desktop and mobile versions have these same UI issues

- [x] Unselected notification button
Expected:
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/3912bc51-99ec-48a1-bf63-e77b3bf78663)
Actual: 
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/313df96c-0374-4b85-8a51-85094956a153)

- [x] Sending queue
Expected:
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/53cd05f0-8142-4d29-966f-a435b154ef26)
Actual: 
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/5fc21a7f-f189-400b-881a-1ea8b76ee1b9)

- [x] Notification cards
Expected:
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/0b32a0ce-6dbd-412c-92c6-8057dc3de036)
Actual: 
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/9d2002fa-0187-4369-b80c-9864944e9915)

- [x] Expanded card
Expected:
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/b47ddbde-3ca4-4cfb-9e93-3110927a83d7)
Actual: 
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/4eef47fb-ea08-46ce-94fa-392b2381733c)

- [x] Missing `!` and `Error` badges
![Ảnh chụp màn hình 2023-10-27 040038](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/448dd579-f6a4-4945-ba51-f7bd09275d90)

- [x] `sending` and `files` must have the first letter uppercase and need to adjust the spacing
Expected:
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/a96885fa-2c0b-42cd-9210-2c80c872feb5)
Actual: 
![image](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/630c90f0-45f2-4b9d-bd77-0c4e7bacf23c)

- [x] All items (including cards and badges) of the mobile version in design seem to have different padding and sizes compared to the desktop one

- [x] Maybe try to use `shrinkWrap` for ListView instead of using fixed height

- [x] Some `fontWeight` are not as same as the design

- [x]  We need to remove the unread counter on the notification icon after tapping in

- [x] About a "Cancel" button - Should we need to add it to the app?
![Ảnh chụp màn hình 2023-10-27 040924](https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/a01ae26c-4a2e-4933-b00b-b5c272bdaff7)

**Comment by sachins-geekyants** [comment]
Updated the design in this PR : https://github.com/atsign-foundation/atmosphere_pro/pull/342

**Comment by sonle-geekyants** [comment]
> Updated the design in this PR : #342

@sachins-geekyants Added some new issues!
