### ISSUE TITLE
move filebin related methods out of SDK into app layer

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/atmosphere_pro#79]
uploadFile, downloadFile methods in at_client_spec and impl should be moved to app layer

**Comment by murali-shris** [comment]
@sachins-geekyants Once you move the method to app, I will deprecate the methods in at client SDK

**Comment by sachins-geekyants** [comment]
all file services are moved to @ mospherePro app.
available in [this](https://github.com/atsign-foundation/atmosphere_pro/tree/feat/file-service-integration) branch.

currently being tested by @pavithragk .

**Comment by sarika01** [comment]
Requires publishing.

**Comment by sachins-geekyants** [comment]
bin related methods are moved to app layer.
